# Precompute illustrative data for vignette tables and charts.
#
# These objects are representative outputs for documentation builds. They are
# not generated by live Azure API calls in CI. They are stored under inst/extdata
# so vignettes can read them without creating a knitr cache directory. The
# moderation examples use the same response shape as
# tests/testthat/fixtures/moderate/*.json. Other objects use plausible values
# with the same columns readers get from foundryR helpers.

cache_dir <- file.path("inst", "extdata", "vignette-cache")
if (!dir.exists(cache_dir)) {
  dir.create(cache_dir, recursive = TRUE)
}

label_severity <- function(severity) {
  ifelse(
    severity == 0,
    "safe",
    ifelse(severity <= 2, "low", ifelse(severity <= 4, "medium", "high"))
  )
}

write_cache <- function(name, value) {
  saveRDS(value, file.path(cache_dir, paste0(name, ".rds")), version = 2)
}

annotation_review <- tibble::tibble(
  respondent_id = 1:6,
  response = c(
    "The lectures were clear, but the weekly quizzes felt rushed.",
    "I liked the examples in R. More office hours would help.",
    "The project made the material practical.",
    "I struggled because the instructions changed late.",
    "The instructor explained regression well.",
    "The course needed more examples before the final exam."
  ),
  sentiment = c("mixed", "positive", "positive", "negative", "positive", "mixed"),
  primary_theme = c(
    "assessment",
    "support",
    "instruction",
    "instruction",
    "instruction",
    "materials"
  ),
  needs_followup = c(TRUE, TRUE, FALSE, TRUE, FALSE, TRUE),
  short_summary = c(
    "Clear lectures, rushed quizzes",
    "R examples helped, office hours requested",
    "Project connected concepts to practice",
    "Late instruction changes caused confusion",
    "Regression explanation was clear",
    "More exam examples requested"
  )
)

write_cache("annotation-workflow", list(review = annotation_review))

similarity_texts <- c(
  "I love programming in R",
  "R is my favorite language for data analysis",
  "The weather is nice today",
  "It is sunny and warm outside"
)

similarity_matrix <- matrix(
  c(
    1.000, 0.912, 0.723, 0.698,
    0.912, 1.000, 0.687, 0.672,
    0.723, 0.687, 1.000, 0.934,
    0.698, 0.672, 0.934, 1.000
  ),
  nrow = 4,
  byrow = TRUE,
  dimnames = list(similarity_texts, similarity_texts)
)

similarity_heatmap <- as.data.frame(as.table(similarity_matrix))
names(similarity_heatmap) <- c("text_1", "text_2", "similarity")
similarity_heatmap <- tibble::as_tibble(similarity_heatmap)

nearest_neighbors <- tibble::tibble(
  rank = 1:3,
  text = c(
    "Data visualization with ggplot2 in R",
    "How to install R packages using install.packages()",
    "Building web applications with Shiny"
  ),
  similarity = c(0.891, 0.812, 0.756)
)

embedding_projection <- tibble::tibble(
  text = c(
    "Python is great for machine learning",
    "R excels at statistical analysis",
    "JavaScript powers modern web applications",
    "SQL is essential for database queries",
    "Italian pasta with tomato sauce",
    "Sushi is a popular Japanese dish",
    "French croissants are flaky and buttery",
    "Mexican tacos with fresh salsa",
    "Soccer is the world's most popular sport",
    "Basketball requires speed and agility",
    "Tennis matches can last for hours",
    "Swimming is excellent cardiovascular exercise"
  ),
  label = c(
    "Python",
    "R",
    "JavaScript",
    "SQL",
    "Pasta",
    "Sushi",
    "Croissant",
    "Tacos",
    "Soccer",
    "Basketball",
    "Tennis",
    "Swimming"
  ),
  topic = rep(c("Programming", "Food", "Sports"), each = 4),
  cluster = rep(1:3, each = 4),
  pc1 = c(-2.2, -1.8, -1.5, -1.1, 0.4, 0.7, 1.1, 1.3, 1.2, 1.6, 1.9, 2.1),
  pc2 = c(1.3, 1.1, 1.5, 0.8, -1.7, -1.2, -1.5, -1.0, 0.3, 0.8, 0.4, 0.9)
)

write_cache(
  "embeddings",
  list(
    similarity_heatmap = similarity_heatmap,
    nearest_neighbors = nearest_neighbors,
    projection = embedding_projection
  )
)

moderate_fixture <- jsonlite::fromJSON(
  file.path("tests", "testthat", "fixtures", "moderate", "response.json"),
  simplifyDataFrame = TRUE
)$categoriesAnalysis

safe_fixture <- jsonlite::fromJSON(
  file.path("tests", "testthat", "fixtures", "moderate", "response_flagged.json"),
  simplifyDataFrame = TRUE
)$categoriesAnalysis

content_safety_results <- dplyr::bind_rows(
  tibble::as_tibble(safe_fixture) |>
    dplyr::mutate(text = "Have a wonderful day!"),
  tibble::as_tibble(moderate_fixture) |>
    dplyr::mutate(text = "This comment targets a group and hints at harm."),
  tibble::tibble(
    category = c("Hate", "Sexual", "SelfHarm", "Violence"),
    severity = c(0L, 0L, 2L, 4L),
    text = "The post describes distress and a violent movie scene."
  ),
  tibble::tibble(
    category = c("Hate", "Sexual", "SelfHarm", "Violence"),
    severity = c(2L, 0L, 0L, 0L),
    text = "The review uses hostile language but does not threaten anyone."
  )
) |>
  dplyr::mutate(label = label_severity(severity)) |>
  dplyr::select(text, category, severity, label)

content_safety_summary <- content_safety_results |>
  dplyr::count(category, label, name = "n") |>
  tidyr::complete(
    category,
    label = c("safe", "low", "medium", "high"),
    fill = list(n = 0L)
  ) |>
  tidyr::pivot_wider(names_from = label, values_from = n, names_prefix = "n_") |>
  dplyr::left_join(
    content_safety_results |>
      dplyr::group_by(category) |>
      dplyr::summarise(max_severity = max(severity), .groups = "drop"),
    by = "category"
  ) |>
  dplyr::arrange(match(category, c("Hate", "Violence", "Sexual", "SelfHarm")))

write_cache(
  "content-safety",
  list(results = content_safety_results, summary = content_safety_summary)
)

tidymodels_metrics <- tibble::tibble(
  .metric = c("accuracy", "roc_auc", "kap", "sensitivity", "specificity"),
  .estimator = "binary",
  .estimate = c(0.875, 0.925, 0.750, 0.900, 0.850),
  .config = "Preprocessor1_Model1"
)

tidymodels_roc <- tibble::tibble(
  .threshold = c(0.00, 0.12, 0.24, 0.37, 0.50, 0.63, 0.76, 0.88, 1.00),
  sensitivity = c(1.00, 1.00, 0.95, 0.90, 0.82, 0.72, 0.55, 0.30, 0.00),
  specificity = c(0.00, 0.35, 0.52, 0.68, 0.80, 0.88, 0.94, 0.98, 1.00),
  .level = "positive"
)

write_cache("tidymodels", list(metrics = tidymodels_metrics, roc = tidymodels_roc))
